apiVersion: observability.parseable.com/v1alpha1
kind: ParseableConfig
metadata:
  labels:
    app.kubernetes.io/name: pai
    app.kubernetes.io/managed-by: kustomize
  name: production
spec:
  namespaceSelector:
    mode: include
    namespaces:
      - demo

  target:
    endpoint: http://106.51.126.91:8010
    credentialsSecret:
      name: parseable-creds
      namespace: parseable-operator-system
    streams:
      traces: prod-traces-demo-new

  instrumentation:
    languages:
      - java
      - python
      - nodejs
      - dotnet
    detectionTimeout: "1m"
