apiVersion: observability.parseable.com/v1alpha1
kind: ParseableConfig
metadata:
  labels:
    app.kubernetes.io/name: pai
    app.kubernetes.io/managed-by: kustomize
  name: production
spec:
  namespaceSelector:
    mode: include
    namespaces:
      - demo

  target:
    endpoint: http://106.51.126.91:8010
    credentialsSecret:
      name: parseable-creds
      namespace: parseable-operator-system
    streams:
      logs: prod-logs
      traces: prod-traces
      metrics: prod-metrics

  instrumentation:
    mode: hybrid
    languages:
      - java
      - python
      - nodejs
      - dotnet
    languageDetection: auto
    detectionTimeout: "2m"

  logs:
    enabled: true
    collector: otel-collector
    enrichment:
      kubernetesMetadata: true

  nodeMetrics:
    enabled: true
    scrapeInterval: "15s"
    collectors:
      - cpu
      - memory
      - disk
      - network

  kubernetesEvents:
    enabled: true
    eventTypes:
      - Warning

  resources:
    daemonSet:
      limits:
        cpu: "1"
        memory: "1Gi"
