apiVersion: observability.parseable.com/v1alpha1
kind: ParseableConfig
metadata:
  labels:
    app.kubernetes.io/name: pai
    app.kubernetes.io/managed-by: kustomize
  name: production-matchlabel
spec:
  namespaceSelector:
    mode: include
    namespaces:
      - demo

  # Include only adservice (Java)
  workloadSelector:
    mode: include
    matchLabels:
      app: adservice

  target:
    endpoint: http://106.51.126.91:8010
    credentialsSecret:
      name: parseable-creds
      namespace: parseable-operator-system
    streams:
      logs: prod-logs
      traces: prod-traces
      metrics: prod-metrics

  instrumentation:
    languages:
      - java
      - python
      - nodejs
      - dotnet
    detectionTimeout: "2m"
